// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: skills/rpc/protobuf/hello_service/interface.proto

package hello_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_skills_rpc_protobuf_hello_service_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_skills_rpc_protobuf_hello_service_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_skills_rpc_protobuf_hello_service_interface_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_skills_rpc_protobuf_hello_service_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_skills_rpc_protobuf_hello_service_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_skills_rpc_protobuf_hello_service_interface_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_skills_rpc_protobuf_hello_service_interface_proto protoreflect.FileDescriptor

const file_skills_rpc_protobuf_hello_service_interface_proto_rawDesc = "" +
	"\n" +
	"1skills/rpc/protobuf/hello_service/interface.proto\x12\x05hello\"\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\" \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value28\n" +
	"\fHelloService\x12(\n" +
	"\x05Hello\x12\x0e.hello.Request\x1a\x0f.hello.ResponseB@Z>122.51.31.227/go-course/go18/skills/rpc/protobuf/hello_serviceb\x06proto3"

var (
	file_skills_rpc_protobuf_hello_service_interface_proto_rawDescOnce sync.Once
	file_skills_rpc_protobuf_hello_service_interface_proto_rawDescData []byte
)

func file_skills_rpc_protobuf_hello_service_interface_proto_rawDescGZIP() []byte {
	file_skills_rpc_protobuf_hello_service_interface_proto_rawDescOnce.Do(func() {
		file_skills_rpc_protobuf_hello_service_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skills_rpc_protobuf_hello_service_interface_proto_rawDesc), len(file_skills_rpc_protobuf_hello_service_interface_proto_rawDesc)))
	})
	return file_skills_rpc_protobuf_hello_service_interface_proto_rawDescData
}

var file_skills_rpc_protobuf_hello_service_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_skills_rpc_protobuf_hello_service_interface_proto_goTypes = []any{
	(*Request)(nil),  // 0: hello.Request
	(*Response)(nil), // 1: hello.Response
}
var file_skills_rpc_protobuf_hello_service_interface_proto_depIdxs = []int32{
	0, // 0: hello.HelloService.Hello:input_type -> hello.Request
	1, // 1: hello.HelloService.Hello:output_type -> hello.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_skills_rpc_protobuf_hello_service_interface_proto_init() }
func file_skills_rpc_protobuf_hello_service_interface_proto_init() {
	if File_skills_rpc_protobuf_hello_service_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skills_rpc_protobuf_hello_service_interface_proto_rawDesc), len(file_skills_rpc_protobuf_hello_service_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skills_rpc_protobuf_hello_service_interface_proto_goTypes,
		DependencyIndexes: file_skills_rpc_protobuf_hello_service_interface_proto_depIdxs,
		MessageInfos:      file_skills_rpc_protobuf_hello_service_interface_proto_msgTypes,
	}.Build()
	File_skills_rpc_protobuf_hello_service_interface_proto = out.File
	file_skills_rpc_protobuf_hello_service_interface_proto_goTypes = nil
	file_skills_rpc_protobuf_hello_service_interface_proto_depIdxs = nil
}
