// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: skills/rpc/protobuf/app_service/interface.proto

package app_service

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	hello_service "122.51.31.227/go-course/go18/skills/rpc/protobuf/hello_service"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// 通过包名引用其他包里面定义
	Request       *hello_service.Request  `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Response      *hello_service.Response `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_skills_rpc_protobuf_app_service_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_skills_rpc_protobuf_app_service_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_skills_rpc_protobuf_app_service_interface_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *App) GetRequest() *hello_service.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *App) GetResponse() *hello_service.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_skills_rpc_protobuf_app_service_interface_proto protoreflect.FileDescriptor

const file_skills_rpc_protobuf_app_service_interface_proto_rawDesc = "" +
	"\n" +
	"/skills/rpc/protobuf/app_service/interface.proto\x12\x03app\x1a1skills/rpc/protobuf/hello_service/interface.proto\"\xa2\x01\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\arequest\x18\x04 \x01(\v2\x0e.hello.RequestR\arequest\x12+\n" +
	"\bresponse\x18\x05 \x01(\v2\x0f.hello.ResponseR\bresponseB>Z<122.51.31.227/go-course/go18/skills/rpc/protobuf/app_serviceb\x06proto3"

var (
	file_skills_rpc_protobuf_app_service_interface_proto_rawDescOnce sync.Once
	file_skills_rpc_protobuf_app_service_interface_proto_rawDescData []byte
)

func file_skills_rpc_protobuf_app_service_interface_proto_rawDescGZIP() []byte {
	file_skills_rpc_protobuf_app_service_interface_proto_rawDescOnce.Do(func() {
		file_skills_rpc_protobuf_app_service_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skills_rpc_protobuf_app_service_interface_proto_rawDesc), len(file_skills_rpc_protobuf_app_service_interface_proto_rawDesc)))
	})
	return file_skills_rpc_protobuf_app_service_interface_proto_rawDescData
}

var file_skills_rpc_protobuf_app_service_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_skills_rpc_protobuf_app_service_interface_proto_goTypes = []any{
	(*App)(nil),                    // 0: app.App
	(*hello_service.Request)(nil),  // 1: hello.Request
	(*hello_service.Response)(nil), // 2: hello.Response
}
var file_skills_rpc_protobuf_app_service_interface_proto_depIdxs = []int32{
	1, // 0: app.App.request:type_name -> hello.Request
	2, // 1: app.App.response:type_name -> hello.Response
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_skills_rpc_protobuf_app_service_interface_proto_init() }
func file_skills_rpc_protobuf_app_service_interface_proto_init() {
	if File_skills_rpc_protobuf_app_service_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skills_rpc_protobuf_app_service_interface_proto_rawDesc), len(file_skills_rpc_protobuf_app_service_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skills_rpc_protobuf_app_service_interface_proto_goTypes,
		DependencyIndexes: file_skills_rpc_protobuf_app_service_interface_proto_depIdxs,
		MessageInfos:      file_skills_rpc_protobuf_app_service_interface_proto_msgTypes,
	}.Build()
	File_skills_rpc_protobuf_app_service_interface_proto = out.File
	file_skills_rpc_protobuf_app_service_interface_proto_goTypes = nil
	file_skills_rpc_protobuf_app_service_interface_proto_depIdxs = nil
}
